# -*- coding: utf-8 -*-
"""preprocessing_data.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrzem0qgxx8gyao0v_aL0g0-_XX9oQej
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Numpy merupakan libary pyton digunakan untuk matriks .
Matlotlib meruopakan untuk presentasi data berupa grafik atau plot 
"""

dataset = pd.read_csv("Musical.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc [:, -1].values

print (x)

print(y)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = "mean")
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEnconder
ct = ColumnTransformer(transformers=[('encoder', OneHotEnconder(), [0])], remainder='passthrough')
x= np.array(ct.fit_transform(x))